### ISSUE TITLE
Nightly channel does not install/update automatically

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-macos#10]
I switched the update frequency to the nightly channel:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1255285/60007627-5b64fe80-967b-11e9-8afe-18705cde7da6.png">

Divvun installer does detect the newly available versions:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1255285/60007790-9ff09a00-967b-11e9-86c2-eed91f8e3e59.png">

But nothing happens without explicitly checking items and clicking the install button.

Expected behavior:

After a restart, all items available for updates should be installed automatically.

**Comment by Trondtr** [comment]
I can confirm that the error reported here is still valid: I get "Update Available", also on frontpage languages (smj), thus the languages have not been updated automatically.

**Comment by snomos** [comment]
This seems to be working now. "Update available" can be displayed if DM has not had enough time to check for updates, download and install the available ones - it needs up to 15 minutes after automatic release before it is installed.

Also, please note that nightly updates will only be installed if the first installation (the manual, first intall) is *also* done using the nightly channel. That is, automatic updates will be done using the channel of the initial installation of a package.
