### ISSUE TITLE
All packages are 1 byte

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-macos#33]
<img width="870" alt="Skjermbilde 2022-03-09 kl  08 21 15" src="https://user-images.githubusercontent.com/1255285/157385065-7d5fed84-4db1-437a-8ec9-644074a249f4.png">

**Comment by SteffenErn** [comment]
Fixed by https://github.com/divvun/taskcluster-gha/pull/2
The file size will update after a package got redeployed. (tested with Old Norse speller)

**Comment by snomos** [comment]
Confirmed.
