### ISSUE TITLE
Divvun Manager appears dead

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-macos#39]
Several users (me included) experience and report that DM often appears stuck with a completely white front page. Nothing happens, nothing visible.

Whatever the reason, there needs to be some sort of feedback to the user, either an error message or a spinning wheel or something - and an error message after some time asking users to restart the app (restarting usually resolves the problem).

Saying nothing makes users very uncomfortable.

**Comment by dylanhand** [comment]
@snomos I believe this was fixed by https://github.com/divvun/divvun-manager-macos/pull/40.

**Comment by snomos** [comment]
I agree, and I have observed the wanted behaviour several times lately. So this is fixed. I close.
